version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: clearml-disit-utils
    container_name: clearml_disit_utils_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /path/to/host/database:/var/www/html/database
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel: